stages:
  - build
  - test

test_1:
  stage: build
  script:
    - echo $CI_COMMIT_REF_NAME
  only:
    - external_pull_requests

test_2:
  stage: test
  script:
    - echo $CI_COMMIT_REF_NAME
  only:
    refs:
      - master
